#!/bin/bash
interval=300               # interval between syncs
keyfile=~/.vdirsyncd.gpg   # GPG encrypted sync password
lockfile=~/.vdirsyncd.pid  # PID file
logfile=~/.vdirsyncd.log   # Log file
verbose=1                  # Default verbose

log() {
   echo "$( date "+%Y/%m/%d %H:%M:%S" ) $*" >> $logfile
}

msg() {
  test $verbose -gt 0 && echo "$*"
}

start() {
   test -f $lockfile && test $(pgrep -c $(basename $0)) -gt 1 && { msg "$0 is already running."; exit 1; }
   password=$(gpg -d $keyfile 2>/dev/null)
   test $? -ne 0 && { msg "Error gettings password."; exit 1; }
   msg "Starting..."
   ( echo $BASHPID > $lockfile
   log "Starting sync every $interval seconds."
   trap "log "Stopping"; rm -f $lockfile" EXIT
   while test 1
   do
      output=$(vdirsyncer -v WARNING sync <<< $password 2>&1)
      test $? -ne 0 && log "Problem syncing. output: $output"
      sleep $interval
   done ) &
}

usage() {
   echo "vdirsyncd [OPTION] <ACTION>"
   echo
   echo "Actions:"
   echo "  start   Start if not yet running"
   echo "  status  Check the current running status"
   echo "  stop    Stop if running"
   echo
   echo "Options:"
   echo "  -i <interval>  Use the specified interval instead of default"
   echo "  -h             Show this usage information"
   echo "  -q             Be quiet"
   exit 1
}

test $# -eq 0 && usage
while test "$1" != ""
do
   case "$1" in
   "-q")
      verbose=0
   ;;
   "-h")
      usage
   ;;
   "-i")
      shift
      interval=$1
   ;;
   "start")
      start
   ;;
   "stop")
      test -f $lockfile && test $(pgrep -c $(basename $0)) -gt 1 && { msg "Stopping..." ; kill $(cat $lockfile); }
   ;;
   "status")
      test -f $lockfile && test $(pgrep -c $(basename $0)) -gt 1 && { msg "Running"; exit 0;} || { msg "Stopped"; exit 1;}
   ;;
   *)
      usage
   ;;
   esac
   shift
done
